name: Multi-platform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -euo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install Tcl/Tk (Linux)
      if: runner.os == 'Linux'
      working-directory: ${{ runner.temp }}
      run: |
        PREFIX=~/.local
        
        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd tcl9.0.3/unix
        ./configure --prefix=$PREFIX --enable-64bit
        make install
        popd

        sudo apt-get update
        sudo apt-get install -y libx11-dev
        
        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd tk9.0.3/unix
        ./configure --prefix=$PREFIX --enable-64bit --with-tcl=${{ runner.temp }}/tcl9.0.3/unix
        make install
        popd
        
        ln -sf ~/.local/bin/tclsh9.0 ~/.local/bin/tclsh
        ln -sf ~/.local/bin/wish9.0 ~/.local/bin/wish

    - name: Configure
      run: |
        PREFIX=~/.local
        
        cmake \
        --preset ci \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_PREFIX_PATH=$PREFIX

    - name: Build
      run: >
        cmake
        --build
        --preset ci
        --verbose

    - name: Lint
      run: >
        curl -LsSf https://astral.sh/uv/install.sh | sh;
        
        cmake
        --build
        --preset ci
        --target tcl_lint
        || echo "Ignored linter violations. For now."

    - name: Test
      run: >
        ctest
        --preset ci
        --verbose
