name: Multi-platform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -euo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: >-
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Tcl/Tk (Linux)
      if: runner.os == 'Linux'
      run: |
        top_dir=$(pwd)
        
        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd ${top_dir}/tcl9.0.3/unix
        ./configure --prefix=${{ github.workspace }}/opt/tcl-tk9 --enable-64bit
        make && sudo make install
        popd

        sudo apt-get update
        sudo apt-get install -y libx11-dev
        
        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd ${top_dir}/tk9.0.3/unix
        ./configure --prefix=${{ github.workspace }}/opt/tcl-tk9 --enable-64bit --with-tcl=${top_dir}/tcl9.0.3/unix
        make && sudo make install
        popd

    - name: Configure CMake
      run: >
        cmake 
        -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        
        -DTCL_LIBRARY=${{ github.workspace }}/opt/tcl-tk9/libtcl9.0.so
        -DTCL_INCLUDE_PATH=${{ github.workspace }}/opt/tcl-tk9/include/
        -DTK_LIBRARY=${{ github.workspace }}/opt/tcl-tk9/lib/libtcl9tk9.0.so
        -DTK_INCLUDE_PATH=${{ github.workspace }}/opt/tcl-tk9/include/
        
        -DTCL_TCLSH=${{ github.workspace }}/opt/tcl-tk9/bin/tclsh
        -DTK_WISH=${{ github.workspace }}/opt/tcl-tk9/bin/wish
        
        -S ${{ github.workspace }}

    - name: Build
      run: >
        cmake 
        --build ${{ steps.strings.outputs.build-output-dir }} 
        --config ${{ matrix.build_type }}
        --verbose

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: >
        PATH=${{ github.workspace }}/opt/tcl-tk9/bin
        ctest 
        --build-config ${{ matrix.build_type }}
        --verbose
