name: build, lint and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  unix-build-and-test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -euo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Set up the environment
      run: |
        echo "DEPS_INSTALL_PREFIX=${{ runner.temp }}/install" >> "$GITHUB_ENV"
        echo "DEPS_BUILD_PREFIX=${{ runner.temp }}/build" >> "$GITHUB_ENV"
        echo "${{ runner.temp }}/install/bin" >> "$GITHUB_PATH"

    - name: Set up the directories
      run: >
        mkdir -p $DEPS_BUILD_PREFIX $DEPS_INSTALL_PREFIX

    - name: Install Tcl/Tk (Linux)
      if: runner.os == 'Linux'
      run: |
        cd $DEPS_BUILD_PREFIX
        
        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd tcl9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --enable-zipfs
        make install
        popd

        sudo apt-get update
        sudo apt-get install -y libx11-dev libxft-dev libfontconfig1-dev libfreetype6-dev libxrender-dev
        
        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd tk9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --enable-zipfs --enable-xft --with-tcl=$DEPS_BUILD_PREFIX/tcl9.0.3/unix
        make install
        popd
        
        ln -sf $DEPS_INSTALL_PREFIX/bin/tclsh9.0 $DEPS_INSTALL_PREFIX/bin/tclsh
        ln -sf $DEPS_INSTALL_PREFIX/bin/wish9.0 $DEPS_INSTALL_PREFIX/bin/wish

    - name: Install Tcl/Tk (macOS)
      if: runner.os == 'macOS'
      run: |
        cd $DEPS_BUILD_PREFIX

        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd tcl9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --enable-zipfs
        make install
        popd

        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd tk9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --enable-zipfs --enable-aqua --with-tcl=$DEPS_BUILD_PREFIX/tcl9.0.3/unix
        make install
        popd

        ln -sf $DEPS_INSTALL_PREFIX/bin/tclsh9.0 $DEPS_INSTALL_PREFIX/bin/tclsh
        ln -sf $DEPS_INSTALL_PREFIX/bin/wish9.0 $DEPS_INSTALL_PREFIX/bin/wish

    - name: Configure
      run: >
        cmake
        --preset ci
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_PREFIX_PATH=$DEPS_INSTALL_PREFIX

    - name: Build
      run: >
        cmake
        --build
        --preset ci
        --verbose

    - name: Lint
      run: |
        curl -LsSf https://astral.sh/uv/install.sh \
        | env UV_INSTALL_DIR=$DEPS_INSTALL_PREFIX/bin bash
        
        cmake \
        --build \
        --preset ci \
        --target tcl_lint \
        || echo "Ignored linter violations. For now."

    - name: Test
      run: >
        ctest
        --preset ci
        --verbose

  windoze-build-and-test:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up the environment
      run: |
        "DEPS_INSTALL_PREFIX=${{ runner.temp }}\\install" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "DEPS_BUILD_PREFIX=${{ runner.temp }}\\build" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "${{ runner.temp }}\\install\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Set up the directories
      run: |
        New-Item -ItemType Directory -Force -Path $env:DEPS_BUILD_PREFIX | Out-Null
        New-Item -ItemType Directory -Force -Path $env:DEPS_INSTALL_PREFIX | Out-Null

    - name: Install Tcl/Tk (Windows)
      run: |
        Set-Location $env:DEPS_BUILD_PREFIX

        curl.exe -L "http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz" -o tcl9.0.3-src.tar.gz
        tar -xzf tcl9.0.3-src.tar.gz
        Push-Location tcl9.0.3\\win
        nmake -f makefile.vc release OPTS=none
        nmake -f makefile.vc install OPTS=none INSTALLDIR=$env:DEPS_INSTALL_PREFIX
        Pop-Location

        curl.exe -L "http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz" -o tk9.0.3-src.tar.gz
        tar -xzf tk9.0.3-src.tar.gz
        Push-Location tk9.0.3\\win
        nmake -f makefile.vc release OPTS=none TCLDIR=..\\..\\tcl9.0.3
        nmake -f makefile.vc install OPTS=none INSTALLDIR=$env:DEPS_INSTALL_PREFIX TCLDIR=..\\..\\tcl9.0.3
        Pop-Location

        if (!(Test-Path "$env:DEPS_INSTALL_PREFIX\\bin\\tclsh.exe")) {
          Copy-Item -Force "$env:DEPS_INSTALL_PREFIX\\bin\\tclsh90.exe" "$env:DEPS_INSTALL_PREFIX\\bin\\tclsh.exe"
        }
        if (!(Test-Path "$env:DEPS_INSTALL_PREFIX\\bin\\wish.exe")) {
          Copy-Item -Force "$env:DEPS_INSTALL_PREFIX\\bin\\wish90.exe" "$env:DEPS_INSTALL_PREFIX\\bin\\wish.exe"
        }

    - name: Configure
      run: |
        cmake --preset ci -DSCIDUP_BUILD_LINTING=OFF

    - name: Build
      run: |
        cmake --build --preset ci --config Release --verbose

    - name: Test
      run: |
        ctest --preset ci -C Release --verbose
