name: Multi-platform CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -euo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Set up the environment
      run: |
        echo "DEPS_INSTALL_PREFIX=${{ runner.temp }}/install/" >> "$GITHUB_ENV"
        echo "DEPS_BUILD_PREFIX=${{ runner.temp }}/build/" >> "$GITHUB_ENV"
        echo "${{ runner.temp }}/install/bin" >> "$GITHUB_PATH"

    - name: Set up the directories
      run: >
        mkdir -p $DEPS_BUILD_PREFIX $DEPS_INSTALL_PREFIX

    - name: Install Tcl/Tk (Linux)
      if: runner.os == 'Linux'
      run: |
        cd $DEPS_BUILD_PREFIX
        
        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd tcl9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit
        make install
        popd

        sudo apt-get update
        sudo apt-get install -y libx11-dev
        
        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd tk9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --with-tcl=$DEPS_BUILD_PREFIX/tcl9.0.3/unix
        make install
        popd
        
        ln -sf $DEPS_INSTALL_PREFIX/bin/tclsh9.0 $DEPS_INSTALL_PREFIX/bin/tclsh
        ln -sf $DEPS_INSTALL_PREFIX/bin/wish9.0 $DEPS_INSTALL_PREFIX/bin/wish

    - name: Install Tcl/Tk (macOS)
      if: runner.os == 'macOS'
      run: |
        cd $DEPS_BUILD_PREFIX

        curl -L http://prdownloads.sourceforge.net/tcl/tcl9.0.3-src.tar.gz | tar -xzf -
        pushd tcl9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit
        make install
        popd

        curl -L http://prdownloads.sourceforge.net/tcl/tk9.0.3-src.tar.gz | tar -xzf -
        pushd tk9.0.3/unix
        ./configure --prefix=$DEPS_INSTALL_PREFIX --enable-64bit --enable-aqua --with-tcl=$DEPS_BUILD_PREFIX/tcl9.0.3/unix
        make install
        popd

        ln -sf $DEPS_INSTALL_PREFIX/bin/tclsh9.0 $DEPS_INSTALL_PREFIX/bin/tclsh
        ln -sf $DEPS_INSTALL_PREFIX/bin/wish9.0 $DEPS_INSTALL_PREFIX/bin/wish

    - name: Configure
      run: >
        cmake
        --preset ci
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_PREFIX_PATH=$DEPS_INSTALL_PREFIX

    - name: Build
      run: >
        cmake
        --build
        --preset ci
        --verbose

    - name: Lint
      run: |
        curl -LsSf https://astral.sh/uv/install.sh \
        | env UV_INSTALL_DIR=$DEPS_INSTALL_PREFIX/bin bash
        
        cmake \
        --build \
        --preset ci \
        --target tcl_lint \
        || echo "Ignored linter violations. For now."

    - name: Test
      run: >
        ctest
        --preset ci
        --verbose
